-- MySQL Script generated by MySQL Workbench
-- Mon Jan  9 22:01:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `IDClient` INT NOT NULL,
  `ClientName` VARCHAR(45) NOT NULL,
  `ClientPhone` VARCHAR(12) NULL,
  PRIMARY KEY (`IDClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Master` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Master` (
  `IDMaster` INT NOT NULL,
  `MasterName` VARCHAR(45) NOT NULL,
  `MasterPhone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`IDMaster`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Procedure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Procedure` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Procedure` (
  `IDProcedure` INT NOT NULL,
  `ProcedureName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDProcedure`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProcedureList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProcedureList` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProcedureList` (
  `IDProcedure` INT NOT NULL,
  `NameProcedure` VARCHAR(20) NOT NULL,
  `ProcedurePrice` REAL NOT NULL,
  `Procedure_IDProcedure` INT NOT NULL,
  PRIMARY KEY (`IDProcedure`),
  INDEX `fk_ProcedureList_Procedure1_idx` (`Procedure_IDProcedure` ASC) VISIBLE,
  CONSTRAINT `fk_ProcedureList_Procedure1`
    FOREIGN KEY (`Procedure_IDProcedure`)
    REFERENCES `mydb`.`Procedure` (`IDProcedure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Schedule` (
  `IDSchedule` INT NOT NULL,
  `Date` DATE NULL,
  `StartTime` TIME NULL,
  `EndTime` TIME NULL,
  `Master_IDMaster` INT NOT NULL,
  PRIMARY KEY (`IDSchedule`),
  INDEX `fk_Schedule_Master1_idx` (`Master_IDMaster` ASC) VISIBLE,
  CONSTRAINT `fk_Schedule_Master1`
    FOREIGN KEY (`Master_IDMaster`)
    REFERENCES `mydb`.`Master` (`IDMaster`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OrderList` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OrderList` (
  `IDOrder` INT NOT NULL,
  `OrderName` VARCHAR(45) NOT NULL,
  `OrderData` DATE NULL,
  `OrderTime` TIME NULL,
  `Client_IDClient` INT NOT NULL,
  `Schedule_IDSchedule` INT NOT NULL,
  `Procedure_IDProcedure` INT NOT NULL,
  PRIMARY KEY (`IDOrder`),
  INDEX `fk_OrderList_Client1_idx` (`Client_IDClient` ASC) VISIBLE,
  INDEX `fk_OrderList_Schedule1_idx` (`Schedule_IDSchedule` ASC) VISIBLE,
  INDEX `fk_OrderList_Procedure1_idx` (`Procedure_IDProcedure` ASC) VISIBLE,
  CONSTRAINT `fk_OrderList_Client1`
    FOREIGN KEY (`Client_IDClient`)
    REFERENCES `mydb`.`Client` (`IDClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderList_Schedule1`
    FOREIGN KEY (`Schedule_IDSchedule`)
    REFERENCES `mydb`.`Schedule` (`IDSchedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderList_Procedure1`
    FOREIGN KEY (`Procedure_IDProcedure`)
    REFERENCES `mydb`.`Procedure` (`IDProcedure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Chek` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Chek` (
  `IDChek` INT NOT NULL,
  `Price` REAL NULL,
  `ChekDate` DATE NULL,
  `ChekClient` VARCHAR(45) NULL,
  PRIMARY KEY (`IDChek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chek_has_OrderList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Chek_has_OrderList` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Chek_has_OrderList` (
  `Chek_IDChek` INT NOT NULL,
  `OrderList_IDOrder` INT NOT NULL,
  PRIMARY KEY (`Chek_IDChek`, `OrderList_IDOrder`),
  INDEX `fk_Chek_has_OrderList_OrderList1_idx` (`OrderList_IDOrder` ASC) VISIBLE,
  INDEX `fk_Chek_has_OrderList_Chek1_idx` (`Chek_IDChek` ASC) VISIBLE,
  CONSTRAINT `fk_Chek_has_OrderList_Chek1`
    FOREIGN KEY (`Chek_IDChek`)
    REFERENCES `mydb`.`Chek` (`IDChek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chek_has_OrderList_OrderList1`
    FOREIGN KEY (`OrderList_IDOrder`)
    REFERENCES `mydb`.`OrderList` (`IDOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chek_has_ProcedureList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Chek_has_ProcedureList` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Chek_has_ProcedureList` (
  `Chek_IDChek` INT NOT NULL,
  `ProcedureList_IDProcedure` INT NOT NULL,
  PRIMARY KEY (`Chek_IDChek`, `ProcedureList_IDProcedure`),
  INDEX `fk_Chek_has_ProcedureList_ProcedureList1_idx` (`ProcedureList_IDProcedure` ASC) VISIBLE,
  INDEX `fk_Chek_has_ProcedureList_Chek1_idx` (`Chek_IDChek` ASC) VISIBLE,
  CONSTRAINT `fk_Chek_has_ProcedureList_Chek1`
    FOREIGN KEY (`Chek_IDChek`)
    REFERENCES `mydb`.`Chek` (`IDChek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chek_has_ProcedureList_ProcedureList1`
    FOREIGN KEY (`ProcedureList_IDProcedure`)
    REFERENCES `mydb`.`ProcedureList` (`IDProcedure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
